upgraded module for python3 support (still compatible w/ python2.X)
epfl-idevelop/ansible-module-openshift pull request #1
Opened 2019-07-11 09:30 UTC by batKem

Types module is absent in python 3 libs, used standard types instead (ie. types.ListType -> list)
Imported sys module to check python version and keep retrocompatibility with 2.x

2019-07-11 10:08 UTC, domq commented
Thanks for your pull request. I am on holiday until next week, and I will
review it then.

Thanks for your understanding, Dominique

-- 
Dominique Quatravaux
dominique@quatravaux.org

Le jeu. 11 juil. 2019 à 11:30, batKem <notifications@github.com> a écrit :

> Types module is absent in python 3 libs, used standard types instead (ie.
> types.ListType -> list)
> Imported sys module to check python version and keep retrocompatibility
> with 2.x
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/epfl-idevelop/ansible-module-openshift/pull/1
> Commit Summary
>
>    - upgraded module for python3 support (still compatible w/ python2.X)
>
> File Changes
>
>    - *M* library/_openshift.py
>    <https://github.com/epfl-idevelop/ansible-module-openshift/pull/1/files#diff-0>
>    (14)
>
> Patch Links:
>
>    -
>    https://github.com/epfl-idevelop/ansible-module-openshift/pull/1.patch
>    - https://github.com/epfl-idevelop/ansible-module-openshift/pull/1.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/epfl-idevelop/ansible-module-openshift/pull/1?email_source=notifications&email_token=AAMN3ENZNANCARPOXK7GUO3P634TXA5CNFSM4IA4WO32YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G6SOC4Q>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAMN3ELHIMNOWXDUTY7ZZSLP634TXANCNFSM4IA4WO3Q>
> .
>

2019-07-15 07:36 UTC, batKem commented
Added optional flag for kubernete object creation that require cluster admin privileges such as persistent volumes and persistent volume claims. The flag's documentation is added to the action_plugins/openshift.py documentation.

2019-07-15 13:31 UTC, domq requested changes

2019-07-15 13:31 UTC, domq commented on library/_openshift.py
> +            if (sys.version_info >= (3,0)):
Comme discuté, regarde https://docs.ansible.com/ansible/2.4/dev_guide/developing_python3.html#bundled-six pour savoir comment faire ce genre de choses à l'aide du module `six`.

En l'espèce, il me semble que la version de la ligne 269 marche dans toutes les versions de Python.

2019-07-15 13:31 UTC, domq commented on library/_openshift.py
> +                return isinstance(u, dict)
Idem ici — Il me semble que la ligne 275 marcherait pour les deux versions de Python à supporter

2019-07-18 17:01 UTC, domq approved these changes

2019-07-24 07:41 UTC, merged